services:
  react-app:
    container_name: react-cypress-develop
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node
      - /home/node/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true