openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger Sample
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /Users/GetRoles:
    post:
      summary: Get user role
      operationId: UserGetRoles
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/GetRolesnRequest'
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRolesResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    GetRolesnRequest:
      type: object
      required:
        - UserName
      properties:
        UserName:
          type: string
    GetRolesResponse:
      type: object
      required:
        - roles
      properties:
        roles:
          type: array
          items:
            type: string 
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string